[profile.release]
strip = true
lto = true

[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = ["-C", "target-feature=+crt-static"]

[env]
RPI_WS281X_SYSROOT = "/usr/arm-linux-gnueabihf"