name: ci

on: [pull_request]

jobs:
  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Add Rustfmt
        run: rustup component add rustfmt
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install dependencies for rs_ws281x
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libclang-dev gcc-arm-linux-gnueabihf
          version: 1.0
      - name: Rust cache
        uses: Swatinem/rust-cache@v1
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install dependencies for rs_ws281x
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libclang-dev gcc-arm-linux-gnueabihf
          version: 1.0
      - name: Rust cache
        uses: Swatinem/rust-cache@v1
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Add Clippy
        run: rustup component add clippy
      - name: Install dependencies for rs_ws281x
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libclang-dev gcc-arm-linux-gnueabihf
          version: 1.0
      - name: Rust cache
        uses: Swatinem/rust-cache@v1
      - name: Install cargo-binstall
        run: wget https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-gnu.tgz -O - | tar -xz -C $HOME/.cargo/bin  
      - name: Install clippy-sarif & sarif-fmt
        run: cargo binstall --no-confirm clippy-sarif sarif-fmt
      - name: Run Clippy
        run: cargo clippy --message-format=json -- -W clippy::pedantic -W clippy::nursery -W clippy::unwrap_used -W clippy::expect_used |
          clippy-sarif | tee results.sarif | sarif-fmt
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif