name: ci

on: [pull_request]

jobs:
  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  build:
    name: Build ARMv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - name: Install dependencies for rs_ws281x
        run: sudo apt update && sudo apt install -y libclang-dev gcc-arm-linux-gnueabihf
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target armv7-unknown-linux-gnueabihf

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - name: Install dependencies for rs_ws281x
        run: sudo apt update && sudo apt install -y libclang-dev gcc-arm-linux-gnueabihf
      - uses: actions-rs/cargo@v1
        with:
          command: test

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - run: rustup component add clippy
      - name: Install dependencies for rs_ws281x
        run: sudo apt update && sudo apt install -y libclang-dev gcc-arm-linux-gnueabihf
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings