name: branch protection

on:
  pull_request:
    types: [opened, edited]

jobs:
  check:
    if: ${{ github.base_ref == 'main' }}
    name: Branch protection
    runs-on: ubuntu-latest
    steps:
      - name: Allowed
        run: echo "Merge allowed."
        if: ${{ github.head_ref == 'dev' }}
      - name: Blocked
        run: echo "Merge blocked." && exit 1
        if: ${{ github.head_ref != 'dev' }}