name: branch protection

on:
  pull_request:

jobs:
  check:
    if: ${{ github.base_ref == 'refs/heads/main' }}
    name: allowed
    runs-on: ubuntu-latest
    steps:
      - name: Allowed
        run: echo "Merge allowed."
        if: ${{ github.source_ref == 'refs/heads/dev' }}
      - name: Blocked
        run: echo "Merge blocked." && exit 1
        if: ${{ github.source_ref != 'refs/heads/dev' }}
