name: release

on:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  check-branch:
    name: Check branch
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps.check.outputs.continue }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check for main branch
        id: "check"
        run: |
          if [[ $(git name-rev --name-only --exclude="tags/*" ${{ github.sha }}) == "remotes/origin/main" ]]; then
            echo "continue release process."
            echo "continue=true" >> $GITHUB_OUTPUT
          else
            echo "release tag on wrong branch."
            echo "continue=false" >> $GITHUB_OUTPUT
          fi

  build-release:
    name: Build release
    runs-on: ubuntu-latest
    needs: ["check-branch"]
    if: ${{ needs.check-branch.outputs.continue == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: arm-unknown-linux-gnueabihf
          toolchain: stable
          profile: minimal
          override: true
      - name: Install dependencies for rs_ws281x
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libclang-dev gcc-arm-linux-gnueabihf
          version: 1.0
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target arm-unknown-linux-gnueabihf
      - name: Safe binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: target/arm-unknown-linux-gnueabihf/release/lighting-manager

  docker-image:
    name: Build image
    runs-on: ubuntu-latest
    needs: ["build-release"]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get binary artifact
        uses: actions/download-artifact@v3
        with:
          name: binary
          path: target/arm-unknown-linux-gnueabihf/release/
      - name: Container registry login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get tags & labels for container
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm/v7
      - name: Build and push container image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: ["build-release"]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get binary artifact
        uses: actions/download-artifact@v3
        with:
          name: binary
          path: target/arm-unknown-linux-gnueabihf/release/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/arm-unknown-linux-gnueabihf/release/lighting-manager
